### ISSUE TITLE
Can't load pgn!

### ISSUE THREAD

**Issue by sjorsvanheuveln** [jbkunst/rchess#5]
When trying to load a pgn, I'm getting this following error. Any idea what's going wrong?

<pre><code>devtools::install_github("jbkunst/rchess")
library("rchess")
pgn <- system.file("~/Desktop/Awesome_Scripts/ChessAnalysis/lichess_ansjovis86_2015-11-21.pgn", package = "rchess")</code></pre>

> file("") only supports open = "w+" and open = "w+b": using the former

**Comment by jbkunst** [comment]
You're using in a wrong way the `system.file` function!

 `system.file`: finds the full file names of files in packages. But your file you want load is not in the package (http://www.inside-r.org/r-doc/base/system.file). 

You need to do something like:

```
pgn <- readLines("~/Desktop/Awesome_Scripts/ChessAnalysis/lichess_ansjovis86_2015-11-21.pgn", warn = FALSE)
pgn <- paste(pgn, collapse = "\n")

chsspgn <- Chess$new()
chsspgn$load_pgn(pgn)
```

Tell me if you can load your pgn ;).

**Comment by sjorsvanheuveln** [comment]
I've actually fixed it as I first thought it was necessary to load it with system.file with the rchess package as argument. But I can load it normally like you said. Is there also a place where you discuss these projects? I'm currently doing machine learning on my own pgns, to understand better where I can improve my game. Perhaps we can share/contribute to each others scripts... ?

**Comment by jbkunst** [comment]
Things related to code like bugs, new features it's better discuss here. If you want talk about ideas in general feel free to email me ;).
