### ISSUE TITLE
Implement a chess engine

### ISSUE THREAD

**Issue by jbkunst** [jbkunst/rchess#6]
Inspired in https://dev.windows.com/en-us/microsoft-edge/testdrive/demos/chess/ it will be fun if we can implement a chess engine like:
- http://p4wn.sourceforge.net/src/fen-test.html
- https://github.com/nmrugg/stockfish.js

**Comment by oganm** [comment]
was fiddling with the idea myself

https://github.com/oganm/stockfisher

**Comment by jbkunst** [comment]
Hi @oganm!

Nice package and nice name ;) it is awesome! Congrats!

So, I can finally close this issue thanks to your package :)
